### ISSUE TITLE
Android Build failed with an exception....

### ISSUE THREAD

**Issue by renntbenrennt** [SXiaoXu/FlutterRealtimeDemo#2]
错误信息如下：
![image](https://user-images.githubusercontent.com/13610283/104704376-8d551e80-5753-11eb-837b-603ade7177d6.png)

我的Flutter doctor -v 信息如下：
![image](https://user-images.githubusercontent.com/13610283/104704523-baa1cc80-5753-11eb-99f1-6cd418384273.png)

**Comment by SXiaoXu** [comment]
你好，看起来是 build.gradle 里面的打包签名配置的问题，已经处理了，您再重新拉取下代码试试。如果还有问题可以按照报错提示修改 build.gradle  中的配置。

**Comment by renntbenrennt** [comment]
@SXiaoXu 好的，我已经pull并测试可以运行了！！！！谢谢你！！！！！！😆😆😆
